const VOCAB_DATA = [
  {id:'v0',type:'vocab',front:'きた',back:'Phía Bắc'},
  {id:'v1',type:'vocab',front:'みなみ',back:'Phía Nam'},
  {id:'v2',type:'vocab',front:'ひがし',back:'Phía Đông'},
  {id:'v3',type:'vocab',front:'にし',back:'Phía Tây'},
  {id:'v4',type:'vocab',front:'まんなか',back:'Chính giữa'},
  {id:'v5',type:'vocab',front:'くるま',back:'Ô tô'},
  {id:'v6',type:'vocab',front:'しんかんせん',back:'Tàu cao tốc'},
  {id:'v7',type:'vocab',front:'でんしゃ',back:'Tàu điện'},
  {id:'v8',type:'vocab',front:'ひこうき',back:'Máy bay'},
  {id:'v9',type:'vocab',front:'えき',back:'Nhà ga'},
  {id:'v10',type:'vocab',front:'まち',back:'Thành phố, thị trấn'},
  {id:'v11',type:'vocab',front:'じかん',back:'Tiếng'},
  {id:'v12',type:'vocab',front:'ふん',back:'Phút'},
  {id:'v13',type:'vocab',front:'じかんはん',back:'Tiếng rưỡi'},
  {id:'v14',type:'vocab',front:'あるいて',back:'Đi bộ'},
  {id:'v15',type:'vocab',front:'くらい',back:'Khoảng'},
  {id:'v16',type:'vocab',front:'どのくらい',back:'Bao lâu'},
  {id:'v17',type:'vocab',front:'じてんしゃ',back:'Xe đạp'},
  {id:'v18',type:'vocab',front:'チョコレート',back:'Chocolate'},
  {id:'v19',type:'vocab',front:'びじゅつかん',back:'Bảo tàng mỹ thuật'},
  {id:'v20',type:'vocab',front:'やま',back:'Núi'},
  {id:'v21',type:'vocab',front:'かわ',back:'Sông'},
  {id:'v22',type:'vocab',front:'おんせん',back:'Suối nước nóng'},
  {id:'v23',type:'vocab',front:'きょうかい',back:'Nhà thờ'},
  {id:'v24',type:'vocab',front:'おしろ',back:'Lâu đài'},
  {id:'v25',type:'vocab',front:'じんじゃ',back:'Đền'},
  {id:'v26',type:'vocab',front:'おてら',back:'Chùa'},
  {id:'v27',type:'vocab',front:'ビル',back:'Toà nhà'},
  {id:'v28',type:'vocab',front:'あたらしい',back:'Mới'},
  {id:'v29',type:'vocab',front:'ふるい',back:'Cũ'},
  {id:'v30',type:'vocab',front:'いい',back:'Tốt'},
  {id:'v31',type:'vocab',front:'よくない',back:'Không tốt'},
  {id:'v32',type:'vocab',front:'わるい',back:'Xấu, tệ'},
  {id:'v33',type:'vocab',front:'おおい',back:'Nhiều'},
  {id:'v34',type:'vocab',front:'すくない',back:'Ít'},
  {id:'v35',type:'vocab',front:'やすい',back:'Rẻ'},
  {id:'v36',type:'vocab',front:'おおきい',back:'To, lớn'},
  {id:'v37',type:'vocab',front:'ちいさい',back:'Nhỏ, bé'},
  {id:'v38',type:'vocab',front:'たかい',back:'Cao, đắt'},
  {id:'v39',type:'vocab',front:'ひくい',back:'Thấp'},
  {id:'v40',type:'vocab',front:'きれい',back:'Đẹp/Sạch sẽ'},
  {id:'v41',type:'vocab',front:'ハンサム',back:'Đẹp trai'},
  {id:'v42',type:'vocab',front:'しずか',back:'Yên tĩnh'},
  {id:'v43',type:'vocab',front:'にぎやか',back:'Náo nhiệt'},
  {id:'v44',type:'vocab',front:'ゆうめい',back:'Nổi tiếng'},
  {id:'v45',type:'vocab',front:'はれ',back:'Nắng'},
  {id:'v46',type:'vocab',front:'くもり',back:'Mây (thời tiết)'},
  {id:'v47',type:'vocab',front:'あめ',back:'Mưa'},
  {id:'v48',type:'vocab',front:'ゆき',back:'Tuyết'},
  {id:'v49',type:'vocab',front:'メロン',back:'Dưa gang (dưa lưới)'},
  {id:'v50',type:'vocab',front:'あたたかい',back:'Ấm áp'},
  {id:'v51',type:'vocab',front:'すずしい',back:'Mát mẻ'},
  {id:'v52',type:'vocab',front:'さむい',back:'Lạnh (thời tiết)'},
  {id:'v53',type:'vocab',front:'つめたい',back:'Lạnh (cảm giác)'},
  {id:'v54',type:'vocab',front:'あつい',back:'Nóng'},
  {id:'v55',type:'vocab',front:'おいしい',back:'Ngon'},
  {id:'v56',type:'vocab',front:'まずい',back:'Dở (món ăn)'},
  {id:'v57',type:'vocab',front:'あまい',back:'Ngọt'},
  {id:'v58',type:'vocab',front:'からい',back:'Cay'},
  {id:'v59',type:'vocab',front:'すっぱい',back:'Chua'},
  {id:'v60',type:'vocab',front:'にがい',back:'Đắng'},
  {id:'v61',type:'vocab',front:'ひ',back:'Ngày / Mặt trời'},
  {id:'v62',type:'vocab',front:'てんきがいい',back:'Thời tiết đẹp'},
  {id:'v63',type:'vocab',front:'てんきがわるい',back:'Thời tiết xấu'},
  {id:'v64',type:'vocab',front:'いちねんじゅう',back:'Suốt 1 năm'},
  {id:'v65',type:'vocab',front:'あまり',back:'Không ~ lắm'},
  {id:'v66',type:'vocab',front:'すこし',back:'Một chút, ít'},
  {id:'v67',type:'vocab',front:'とても',back:'Rất'},
  {id:'v68',type:'vocab',front:'どう',back:'Thế nào'},
  {id:'v69',type:'vocab',front:'そうですね',back:'Đồng tình với người khác'},
  {id:'v70',type:'vocab',front:'たいへん',back:'Cực kỳ, vô cùng'},
  {id:'v71',type:'vocab',front:'ぜんぜん',back:'Hoàn toàn, không'},
  {id:'v72',type:'vocab',front:'しんせつ',back:'Tốt bụng'},
  {id:'v73',type:'vocab',front:'ところ',back:'Nơi, chỗ'},
  {id:'v74',type:'vocab',front:'ひと',back:'Người'},
  {id:'v75',type:'vocab',front:'みどり',back:'Màu xanh, cây xanh'},
  {id:'v76',type:'vocab',front:'あります',back:'Có'},
  {id:'v77',type:'vocab',front:'そして',back:'Và'},
  {id:'v78',type:'vocab',front:'きょう',back:'Hôm nay'},
  {id:'v79',type:'vocab',front:'あした',back:'Ngày mai'},
  {id:'v80',type:'vocab',front:'あっさて',back:'Ngày kia'},
  {id:'v81',type:'vocab',front:'きのう',back:'Hôm qua'},
  {id:'v82',type:'vocab',front:'おととい',back:'Hôm kia'},
  {id:'v83',type:'vocab',front:'せんしゅう',back:'Tuần trước'},
  {id:'v84',type:'vocab',front:'しゅうまつ',back:'Cuối tuần'},
  {id:'v85',type:'vocab',front:'いえ',back:'Nhà'},
  {id:'v86',type:'vocab',front:'へや',back:'Căn phòng'},
  {id:'v87',type:'vocab',front:'デパート',back:'Trung tâm thương mại'},
  {id:'v88',type:'vocab',front:'ゲーム',back:'Trò chơi'},
  {id:'v89',type:'vocab',front:'かぞく',back:'Gia đình'},
  {id:'v90',type:'vocab',front:'こいびと',back:'Người yêu'},
  {id:'v91',type:'vocab',front:'ともだち',back:'Bạn bè'},
  {id:'v92',type:'vocab',front:'ルームメイト',back:'Bạn cùng phòng'},
  {id:'v93',type:'vocab',front:'どこか（へ）',back:'Nơi nào đó'},
  {id:'v94',type:'vocab',front:'あいます',back:'Gặp gỡ'},
  {id:'v95',type:'vocab',front:'つくります',back:'Làm, chế tạo'},
  {id:'v96',type:'vocab',front:'かいものします',back:'Mua sắm'},
  {id:'v97',type:'vocab',front:'しょくじします',back:'Dùng bữa, ăn uống'},
  {id:'v98',type:'vocab',front:'せんたくします',back:'Giặt giũ'},
  {id:'v99',type:'vocab',front:'そうじします',back:'Hút bụi, lau dọn nhà cửa'},
  {id:'v100',type:'vocab',front:'それから',back:'Sau đó'},
  {id:'v101',type:'vocab',front:'ひとりで',back:'Một mình'},
  {id:'v102',type:'vocab',front:'ばんごはん',back:'Bữa cơm tối'},
  {id:'v103',type:'vocab',front:'かぜ',back:'Cảm cúm'},
  {id:'v104',type:'vocab',front:'てんき',back:'Thời tiết'},
  {id:'v105',type:'vocab',front:'ふく',back:'Quần áo'},
  {id:'v106',type:'vocab',front:'のぼります',back:'Leo trèo'},
  {id:'v107',type:'vocab',front:'はいります',back:'Vào, bước vào'},
  {id:'v108',type:'vocab',front:'たいへん',back:'Vất vả'},
  {id:'v109',type:'vocab',front:'おもしろい',back:'Thú vị'},
  {id:'v110',type:'vocab',front:'つまらない',back:'Chán'},
  {id:'v111',type:'vocab',front:'きもちがいい',back:'Cảm thấy sảng khoái'},
  {id:'v112',type:'vocab',front:'たのしい',back:'Vui vẻ'},
  {id:'v113',type:'vocab',front:'むずかしい',back:'Khó'},
  {id:'v114',type:'vocab',front:'やさしい',back:'Dễ'},
  {id:'v115',type:'vocab',front:'いそがしい',back:'Bận'},
  {id:'v116',type:'vocab',front:'ひま',back:'Rảnh rỗi'},
  {id:'v117',type:'vocab',front:'え',back:'Tranh'},
  {id:'v118',type:'vocab',front:'アニメ',back:'Phim hoạt hình'},
  {id:'v119',type:'vocab',front:'とります',back:'Chụp ảnh'},
  {id:'v120',type:'vocab',front:'かります',back:'Vay, mượn'},
  {id:'v121',type:'vocab',front:'ほしい',back:'Muốn có'},
  {id:'v122',type:'vocab',front:'すき',back:'Thích'},
  {id:'v123',type:'vocab',front:'きらい',back:'Ghét'},
  {id:'v124',type:'vocab',front:'こんげつ',back:'Tháng này'},
  {id:'v125',type:'vocab',front:'らいげつ',back:'Tháng sau'},
  {id:'v126',type:'vocab',front:'いきます',back:'Đi'},
  {id:'v127',type:'vocab',front:'きます',back:'Đến'},
  {id:'v128',type:'vocab',front:'かえります',back:'Về'},
  {id:'v129',type:'vocab',front:'ひる',back:'Buổi trưa'},
  {id:'v130',type:'vocab',front:'けさ',back:'Sáng nay'},
  {id:'v131',type:'vocab',front:'せんげつ',back:'Tháng trước'},
  {id:'v132',type:'vocab',front:'きょねん',back:'Năm ngoái'},
  {id:'v133',type:'vocab',front:'かんたん',back:'Dễ, đơn giản'},
  {id:'v134',type:'vocab',front:'どうして',back:'Tại sao'},
  {id:'v135',type:'vocab',front:'こんど',back:'Lần tới'},
  {id:'v136',type:'vocab',front:'こんばん',back:'Tối nay'},
  {id:'v137',type:'vocab',front:'ことし',back:'Năm nay'},
  {id:'v138',type:'vocab',front:'らいねん',back:'Sang năm'},
  {id:'v139',type:'vocab',front:'けしき',back:'Phong cảnh'},
  {id:'v140',type:'vocab',front:'しゃしん',back:'Ảnh'},
  {id:'v141',type:'vocab',front:'こんしゅう',back:'Tuần này'},
  {id:'v142',type:'vocab',front:'らいしゅう',back:'Tuần sau'},
  {id:'v143',type:'vocab',front:'おかね',back:'Tiền'},
  {id:'v144',type:'vocab',front:'たくさん',back:'nhiều (trạng từ)'},
  {id:'v145',type:'vocab',front:'やすみ',back:'Ngày nghỉ'},
  {id:'v146',type:'vocab',front:'よる',back:'Buổi tối'},
  {id:'v147',type:'vocab',front:'ねむい',back:'Buồn ngủ'},
  {id:'v148',type:'vocab',front:'オーストラリア',back:'Úc'},
  {id:'v149',type:'vocab',front:'きょうし',back:'Giáo viên'},
  {id:'v150',type:'vocab',front:'しゅみ',back:'Sở thích'},
  {id:'v151',type:'vocab',front:'スポーツ',back:'Thể thao'},
  {id:'v152',type:'vocab',front:'サッカー',back:'Bóng đá'},
  {id:'v153',type:'vocab',front:'すいえい',back:'Bơi lội'},
  {id:'v154',type:'vocab',front:'インフォメーション',back:'Quầy thông tin'},
  {id:'v155',type:'vocab',front:'エレベーター',back:'Thang máy'},
  {id:'v156',type:'vocab',front:'エスカレーター',back:'Thang cuốn'},
  {id:'v157',type:'vocab',front:'きつえんしょ',back:'Nơi hút thuốc'},
  {id:'v158',type:'vocab',front:'きっさてん',back:'Quán giải khát'},
  {id:'v159',type:'vocab',front:'ちか',back:'Ngầm, dưới lòng đất'},
  {id:'v160',type:'vocab',front:'でんしじしょ',back:'Kim từ điển'},
  {id:'v161',type:'vocab',front:'けしごむ',back:'Tẩy'},
  {id:'v162',type:'vocab',front:'あぶら',back:'Dầu'},
  {id:'v163',type:'vocab',front:'こめ',back:'Gạo'},
  {id:'v164',type:'vocab',front:'てんいん',back:'Nhân viên bán hàng'},
  {id:'v165',type:'vocab',front:'いらっしゃいませ',back:'Kính chào quý khách'},
  {id:'v166',type:'vocab',front:'～や',back:'Cửa hàng ~, Hiệu ~'},
  {id:'v167',type:'vocab',front:'ズボン',back:'Quần dài'},
  {id:'v168',type:'vocab',front:'かばん',back:'Cặp, túi xách'},
  {id:'v169',type:'vocab',front:'Tシャツ',back:'Áo phông'},
  {id:'v170',type:'vocab',front:'とけい',back:'Đồng hồ'},
  {id:'v171',type:'vocab',front:'いくら',back:'Bao nhiêu tiền'},
  {id:'v172',type:'vocab',front:'やさい',back:'Rau'},
  {id:'v173',type:'vocab',front:'いちご',back:'Quả dâu'},
  {id:'v174',type:'vocab',front:'りんご',back:'Quả táo'},
  {id:'v175',type:'vocab',front:'カレー',back:'Món cà-ri'},
  {id:'v176',type:'vocab',front:'とんかつ',back:'Món thịt lợn chiên xù'},
  {id:'v177',type:'vocab',front:'コーヒー',back:'Cà phê'},
  {id:'v178',type:'vocab',front:'こうちゃ',back:'Trà đen'},
  {id:'v179',type:'vocab',front:'おちゃ',back:'Trà, nước chè'},
  {id:'v180',type:'vocab',front:'ドイツ',back:'Đức'},
  {id:'v181',type:'vocab',front:'さいふ',back:'Ví tiền'},
  {id:'v182',type:'vocab',front:'だれ',back:'Ai'},
  {id:'v183',type:'vocab',front:'たいいくかん',back:'Nhà thi đấu, nhà tập thể dục'},
  {id:'v184',type:'vocab',front:'としょかん',back:'Thư viện'},
  {id:'v185',type:'vocab',front:'びょういん',back:'Bệnh viện'},
  {id:'v186',type:'vocab',front:'ゆうびんきょく',back:'Bưu điện'},
  {id:'v187',type:'vocab',front:'じゅぎょう',back:'Giờ học'},
  {id:'v188',type:'vocab',front:'アルバイト',back:'Việc làm thêm'},
  {id:'v189',type:'vocab',front:'スケジュール',back:'Kế hoạch, lịch'},
  {id:'v190',type:'vocab',front:'パーティー',back:'Bữa tiệc'},
  {id:'v191',type:'vocab',front:'バーベキュー',back:'Tiệc nước ngoài trời'},
  {id:'v192',type:'vocab',front:'はなび',back:'Pháo hoa'},
  {id:'v193',type:'vocab',front:'ホームステイ',back:'Ở cùng gia đình bản địa'},
  {id:'v194',type:'vocab',front:'まつり',back:'Lễ hội'},
  {id:'v195',type:'vocab',front:'はる',back:'Mùa xuân'},
  {id:'v196',type:'vocab',front:'なつ',back:'Mùa hè'},
  {id:'v197',type:'vocab',front:'あき',back:'Mùa thu'},
  {id:'v198',type:'vocab',front:'ふゆ',back:'Mùa đông'},
  {id:'v199',type:'vocab',front:'ぎゅうにゅう',back:'Sữa bò'},
  {id:'v200',type:'vocab',front:'くだもの',back:'Hoa quả, trái cây'},
  {id:'v201',type:'vocab',front:'インターネット',back:'Mạng internet'},
  {id:'v202',type:'vocab',front:'はたらきます',back:'Làm việc, lao động'},
  {id:'v203',type:'vocab',front:'よみます',back:'Đọc'},
  {id:'v204',type:'vocab',front:'ねます',back:'Ngủ'},
  {id:'v205',type:'vocab',front:'えいが',back:'Phim (điện ảnh)'},
  {id:'v206',type:'vocab',front:'まいつき',back:'Mỗi tháng'},
  {id:'v207',type:'vocab',front:'カラオケ',back:'Hát karaoke'},
  {id:'v208',type:'vocab',front:'コンサート',back:'Hoà nhạc'},
  {id:'v209',type:'vocab',front:'しあい',back:'Trận đấu'},
  {id:'v210',type:'vocab',front:'セール',back:'Giảm giá'},
  {id:'v211',type:'vocab',front:'チケット',back:'Vé'},
  {id:'v212',type:'vocab',front:'ちず',back:'Bản đồ'},
  {id:'v213',type:'vocab',front:'ドライブ',back:'Lái xe'},
  {id:'v214',type:'vocab',front:'みずぎ',back:'Đồ bơi'},
  {id:'v215',type:'vocab',front:'やきゅう',back:'Bóng chày'},
  {id:'v216',type:'vocab',front:'やくそく',back:'Hứa, hẹn'},
  {id:'v217',type:'vocab',front:'ようじ',back:'Việc bận'},
  {id:'v218',type:'vocab',front:'～まい',back:'Cách đếm vật mỏng, phẳng'},
  {id:'v219',type:'vocab',front:'ざんねん',back:'Tiếc'},
  {id:'v220',type:'vocab',front:'いっしょに',back:'Cùng với'},
  {id:'v221',type:'vocab',front:'いいですね',back:'Hay đấy, được đấy'},
  {id:'v222',type:'vocab',front:'すみません',back:'Xin lỗi'},
  {id:'v223',type:'vocab',front:'またこんど',back:'Hẹn anh lần sau'},
  {id:'v224',type:'vocab',front:'たべもの',back:'Đồ ăn'},
  {id:'v225',type:'vocab',front:'のみもの',back:'Đồ uống'},
  {id:'v226',type:'vocab',front:'やきにく',back:'Thịt nướng'},
  {id:'v227',type:'vocab',front:'ラーメン',back:'Mỳ Nhật'},
  {id:'v228',type:'vocab',front:'たべほうだい',back:'Ăn buffet'},
  {id:'v229',type:'vocab',front:'コース',back:'Suất ăn / Khoá học'},
  {id:'v230',type:'vocab',front:'いざかや',back:'Quán rượu'},
  {id:'v231',type:'vocab',front:'えいがかん',back:'Rạp chiếu phim'},
  {id:'v232',type:'vocab',front:'ちかてつ',back:'Tàu điện ngầm'},
  {id:'v233',type:'vocab',front:'かしゅ',back:'Ca sỹ'},
  {id:'v234',type:'vocab',front:'きせつ',back:'Mùa'},
  {id:'v235',type:'vocab',front:'コメディー',back:'Hài kịch'},
  {id:'v236',type:'vocab',front:'ジャズ',back:'Nhạc jazz'},
  {id:'v237',type:'vocab',front:'ツアー',back:'Tour du lịch'},
  {id:'v238',type:'vocab',front:'どちら',back:'Bên nào, phương nào'},
  {id:'v239',type:'vocab',front:'どちらも',back:'Bên nào cũng'},
  {id:'v240',type:'vocab',front:'ちかい',back:'Gần'},
  {id:'v241',type:'vocab',front:'とおい',back:'Xa'},
  {id:'v242',type:'vocab',front:'はやい',back:'Sớm'},
  {id:'v243',type:'vocab',front:'ひろい',back:'Rộng'},
  {id:'v244',type:'vocab',front:'いちばん',back:'Nhất'},
  {id:'v245',type:'vocab',front:'ぜんぶ',back:'Toàn bộ'},
  {id:'v246',type:'vocab',front:'そうですねえ',back:'Câu nói ngập ngừng khi suy nghĩ để trả lời câu hỏi'},
  {id:'v247',type:'vocab',front:'おこのみやき',back:'Món bánh xèo Nhật'},
  {id:'v248',type:'vocab',front:'すきやき',back:'Món nhúng có thịt bò và rau'},
  {id:'v249',type:'vocab',front:'あそびます',back:'Chơi'},
  {id:'v250',type:'vocab',front:'ぜひ',back:'Nhất định'},
  {id:'v251',type:'vocab',front:'まだ',back:'Vẫn, chưa'},
  {id:'v252',type:'vocab',front:'もう',back:'Đã, rồi'},
  {id:'v253',type:'vocab',front:'そうしましょう',back:'Làm như thế đi'},
  {id:'v254',type:'vocab',front:'わかりました',back:'Tôi hiểu rồi'},
  {id:'v255',type:'vocab',front:'せまい',back:'Bé, chật'},
  {id:'v256',type:'vocab',front:'ちょっと',back:'Hơn/Kém một chút'},
  {id:'v257',type:'vocab',front:'ずっと',back:'Hơn/Kém Rất nhiều'},
  {id:'v258',type:'vocab',front:'じょうず',back:'Giỏi'},
  {id:'v259',type:'vocab',front:'くすり',back:'Thuốc'},
  {id:'v260',type:'vocab',front:'おそい',back:'Trễ'},
  {id:'v261',type:'vocab',front:'ほっかいどう',back:'Hokkaido'}
];