const VOCAB_DATA = [
  {id:'v0',type:'vocab',front:'きた',back:'Phía bắc',kanji:'北',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v1',type:'vocab',front:'みなみ',back:'Phía nam',kanji:'南',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v2',type:'vocab',front:'ひがし',back:'Phía đông',kanji:'東',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v3',type:'vocab',front:'にし',back:'Phía tây',kanji:'西',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v4',type:'vocab',front:'まんなか',back:'Chính giữa',kanji:'真ん中',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v5',type:'vocab',front:'くるま',back:'Ô tô',kanji:'車',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v6',type:'vocab',front:'しんかんせん',back:'Tàu cao tốc Shinkansen',kanji:'新幹線',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v7',type:'vocab',front:'でんしゃ',back:'Tàu điện',kanji:'電車',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v8',type:'vocab',front:'ひこうき',back:'Máy bay',kanji:'飛行機',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v9',type:'vocab',front:'えき',back:'Nhà ga',kanji:'駅',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v10',type:'vocab',front:'まち',back:'Thành phố, thị trấn',kanji:'町',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v11',type:'vocab',front:'あるいて',back:'Đi bộ',kanji:'歩いて',lesson:'Lesson_04',sub:'Sub_01_Noi_Chon_Huong_Vi'},
  {id:'v12',type:'vocab',front:'おんせん',back:'Suối nước nóng',kanji:'温泉',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v13',type:'vocab',front:'かわ',back:'Sông',kanji:'川',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v14',type:'vocab',front:'やま',back:'Núi',kanji:'山',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v15',type:'vocab',front:'きょうkai',back:'Nhà thờ',kanji:'教会',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v16',type:'vocab',front:'おしろ',back:'Lâu đài, thành',kanji:'お城',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v17',type:'vocab',front:'じんじゃ',back:'Đền',kanji:'神社',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v18',type:'vocab',front:'おてら',back:'Chùa',kanji:'お寺',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v19',type:'vocab',front:'びる',back:'Tòa nhà',kanji:'ビル',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v20',type:'vocab',front:'ところ',back:'Nơi, chỗ',kanji:'ところ',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v21',type:'vocab',front:'ひと',back:'Người',kanji:'人',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v22',type:'vocab',front:'みどり',back:'Màu xanh; Cây xanh',kanji:'緑',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v23',type:'vocab',front:'ある',back:'Có',kanji:'あります',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v24',type:'vocab',front:'あたらしい',back:'Mới',kanji:'新しい',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v25',type:'vocab',front:'ふるい',back:'Cũ',kanji:'古い',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v26',type:'vocab',front:'いい',back:'Tốt',kanji:'いい',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v27',type:'vocab',front:'おおい',back:'Nhiều',kanji:'多い',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v28',type:'vocab',front:'すくない',back:'Ít',kanji:'少ない',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v29',type:'vocab',front:'おおきい',back:'To, lớn',kanji:'大きい',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v30',type:'vocab',front:'ちいさい',back:'Nhỏ, bé',kanji:'小さい',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v31',type:'vocab',front:'たかい',back:'Cao, đắt',kanji:'高い',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v32',type:'vocab',front:'ひくい',back:'Thấp',kanji:'低い',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v33',type:'vocab',front:'きれい',back:'Đẹp, sạch sẽ',kanji:'きれい',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v34',type:'vocab',front:'しずか',back:'Yên tĩnh',kanji:'静か',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v35',type:'vocab',front:'にぎやか',back:'Náo nhiệt, nhộn nhịp',kanji:'にぎやか',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v36',type:'vocab',front:'ゆうめい',back:'Nổi tiếng',kanji:'有名',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v37',type:'vocab',front:'どんな',back:'Như thế nào',kanji:'どんな',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v38',type:'vocab',front:'てがみ',back:'Thư, lá thư',kanji:'手紙',lesson:'Lesson_04',sub:'Sub_02_Dac_Diem_Noi_Chon'},
  {id:'v39',type:'vocab',front:'あめ',back:'Mưa',kanji:'雨',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v40',type:'vocab',front:'ゆき',back:'Tuyết',kanji:'雪',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v41',type:'vocab',front:'ひ',back:'Ngày / Mặt trời',kanji:'日',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v42',type:'vocab',front:'めろん',back:'Dưa gang (dưa lưới)',kanji:'メロン',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v43',type:'vocab',front:'あたたかい',back:'Ấm áp (thời tiết)',kanji:'暖かい',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v44',type:'vocab',front:'すずしい',back:'Mát mẻ',kanji:'涼しい',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v45',type:'vocab',front:'あつい',back:'Nóng bức (thời tiết)',kanji:'暑い',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v46',type:'vocab',front:'さむい',back:'Lạnh, rét (thời tiết)',kanji:'寒い',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v47',type:'vocab',front:'てんきがいい',back:'Thời tiết đẹp',kanji:'天気がいい',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v48',type:'vocab',front:'てんきがわるい',back:'Thời tiết xấu',kanji:'天気がわるい',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v49',type:'vocab',front:'あたたかい',back:'Ấm (nhiệt độ, cảm giác)',kanji:'温かい',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v50',type:'vocab',front:'あつい',back:'Nóng (nhiệt độ)',kanji:'熱い',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v51',type:'vocab',front:'つめたい',back:'Lạnh / Mát (nhiệt độ)',kanji:'冷たい',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v52',type:'vocab',front:'おいしい',back:'Ngon',kanji:'おいしい',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v53',type:'vocab',front:'あまい',back:'Ngọt',kanji:'甘い',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v54',type:'vocab',front:'からい',back:'Cay',kanji:'辛い',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v55',type:'vocab',front:'にがい',back:'Đắng',kanji:'苦い',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v56',type:'vocab',front:'すっぱい',back:'Chua',kanji:'すっぱい',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v57',type:'vocab',front:'いちねんじゅう',back:'Suốt 1 năm',kanji:'一年中',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v58',type:'vocab',front:'あまり',back:'Không lắm',kanji:'あまり',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v59',type:'vocab',front:'すこし',back:'Một chút, ít',kanji:'少し',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v60',type:'vocab',front:'とても',back:'Rất',kanji:'とても',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v61',type:'vocab',front:'どう',back:'Thế nào',kanji:'どう',lesson:'Lesson_04',sub:'Sub_03_Thoi_Tiet_Va_Mon_An'},
  {id:'v62',type:'vocab',front:'きょう',back:'Hôm nay',kanji:'今日',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v63',type:'vocab',front:'あした',back:'Ngày mai',kanji:'明日',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v64',type:'vocab',front:'あさって',back:'Ngày kia',kanji:'あさって',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v65',type:'vocab',front:'きのう',back:'Hôm qua',kanji:'昨日',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v66',type:'vocab',front:'おととい',back:'Hôm kia',kanji:'おととい',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v67',type:'vocab',front:'せんしゅう',back:'Tuần trước',kanji:'先週',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v68',type:'vocab',front:'しゅうまつ',back:'Cuối tuần',kanji:'週末',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v69',type:'vocab',front:'いえ',back:'Nhà',kanji:'家',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v70',type:'vocab',front:'へや',back:'Căn phòng',kanji:'部屋',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v71',type:'vocab',front:'でぱーt',back:'Trung tâm thương mại',kanji:'デパート',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v72',type:'vocab',front:'びじゅつかん',back:'Bảo tàng mỹ thuật',kanji:'美術館',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v73',type:'vocab',front:'げーむ',back:'Trò chơi',kanji:'ゲーム',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v74',type:'vocab',front:'かぞく',back:'Gia đình',kanji:'家族',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v75',type:'vocab',front:'こいびと',back:'Người yêu',kanji:'恋人',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v76',type:'vocab',front:'ともだち',back:'Bạn bè',kanji:'友達',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v77',type:'vocab',front:'るーむめいと',back:'Bạn cùng phòng',kanji:'ルームメイト',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v78',type:'vocab',front:'どこか',back:'Nơi nào đó',kanji:'どこか',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v79',type:'vocab',front:'あいます',back:'Gặp gỡ',kanji:'会います',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v80',type:'vocab',front:'つくります',back:'Làm, chế tạo',kanji:'作ります',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v81',type:'vocab',front:'kaiものします',back:'Mua sắm',kanji:'買い物します',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v82',type:'vocab',front:'しょくじします',back:'Dùng bữa, ăn uống',kanji:'食事します',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v83',type:'vocab',front:'せんたくします',back:'Giặt giũ',kanji:'洗濯します',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v84',type:'vocab',front:'そうじします',back:'Hút bụi, lau dọn nhà cửa',kanji:'掃除します',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v85',type:'vocab',front:'それから',back:'Sau đó',kanji:'それから',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v86',type:'vocab',front:'ひとりで',back:'Một mình',kanji:'一人で',lesson:'Lesson_05',sub:'Sub_01_Ke_Hoach_Ngay_Nghi'},
  {id:'v87',type:'vocab',front:'けさ',back:'Sáng nay',kanji:'今朝',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v88',type:'vocab',front:'せんげつ',back:'Tháng trước',kanji:'先月',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v89',type:'vocab',front:'きょねん',back:'Năm ngoái',kanji:'去年',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v90',type:'vocab',front:'かぜ',back:'Cảm cúm',kanji:'風邪',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v91',type:'vocab',front:'てんき',back:'Thời tiết',kanji:'天気',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v92',type:'vocab',front:'ばんごはん',back:'Cơm tối',kanji:'晩ご飯',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v93',type:'vocab',front:'ふく',back:'Quần áo',kanji:'服',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v94',type:'vocab',front:'のぼります',back:'Leo, trèo',kanji:'登ります',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v95',type:'vocab',front:'はいります',back:'Vào / Bước vào',kanji:'入ります',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v96',type:'vocab',front:'いそがしい',back:'Bận rộn',kanji:'忙しい',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v97',type:'vocab',front:'おもしろい',back:'Thú vị, hay, hấp dẫn',kanji:'おもしろい',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v98',type:'vocab',front:'きもちがいい',back:'Cảm thấy sảng khoái',kanji:'気持ちがいい',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v99',type:'vocab',front:'やすい',back:'Rẻ',kanji:'安い',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v100',type:'vocab',front:'たのしい',back:'Vui vẻ',kanji:'楽しい',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v101',type:'vocab',front:'むずかしい',back:'Khó',kanji:'難しい',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v102',type:'vocab',front:'かんたん',back:'Dễ, đơn giản',kanji:'簡単',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v103',type:'vocab',front:'たいhen',back:'Vất vả, khổ sở',kanji:'大変',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v104',type:'vocab',front:'ひま',back:'Rảnh rỗi',kanji:'暇',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v105',type:'vocab',front:'どうして',back:'Tại sao',kanji:'どうして',lesson:'Lesson_05',sub:'Sub_02_Sau_Ky_Nghi'},
  {id:'v106',type:'vocab',front:'こんど',back:'Lần này, lần tới',kanji:'今度',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v107',type:'vocab',front:'こんばん',back:'Tối nay',kanji:'今晩',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v108',type:'vocab',front:'ことし',back:'Năm nay',kanji:'今年',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v109',type:'vocab',front:'らいねん',back:'Sang năm',kanji:'来年',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v110',type:'vocab',front:'あにめ',back:'Hoạt hình',kanji:'アニメ',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v111',type:'vocab',front:'え',back:'Tranh, bức tranh',kanji:'絵',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v112',type:'vocab',front:'けしき',back:'Phong cảnh',kanji:'景色',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v113',type:'vocab',front:'じてんしゃ',back:'Xe đạp',kanji:'自転車',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v114',type:'vocab',front:'しゃしん',back:'Ảnh, bức ảnh',kanji:'写真',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v115',type:'vocab',front:'とります',back:'Chụp (ảnh), quay (video)',kanji:'撮ります',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v116',type:'vocab',front:'かります',back:'Vay, mượn',kanji:'借ります',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v117',type:'vocab',front:'ほしい',back:'Muốn có',kanji:'ほしい',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v118',type:'vocab',front:'すki',back:'Thích',kanji:'好き',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v119',type:'vocab',front:'きらい',back:'Ghét',kanji:'嫌い',lesson:'Lesson_05',sub:'Sub_03_Ky_Nghi_Sap_Toi'},
  {id:'v120',type:'vocab',front:'こんしゅう',back:'Tuần này',kanji:'今週',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v121',type:'vocab',front:'らいしゅう',back:'Tuần sau',kanji:'来週',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v122',type:'vocab',front:'こんげつ',back:'Tháng này',kanji:'今月',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v123',type:'vocab',front:'らいげつ',back:'Tháng sau',kanji:'来月',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v124',type:'vocab',front:'からおけ',back:'Hát karaoke',kanji:'カラオケ',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v125',type:'vocab',front:'こんさーと',back:'Buổi hòa nhạc',kanji:'コンサート',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v126',type:'vocab',front:'しai',back:'Trận đấu',kanji:'試合',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v127',type:'vocab',front:'せーる',back:'Giảm giá',kanji:'セール',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v128',type:'vocab',front:'ちけっと',back:'Vé',kanji:'チケット',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v129',type:'vocab',front:'ちず',back:'Bản đồ',kanji:'地図',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v130',type:'vocab',front:'どらいぶ',back:'Lái xe',kanji:'ドライブ',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v131',type:'vocab',front:'みずぎ',back:'Đồ bơi',kanji:'水着',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v132',type:'vocab',front:'やきゅう',back:'Bóng chày',kanji:'野球',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v133',type:'vocab',front:'やくそく',back:'Hứa, hẹn',kanji:'約束',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v134',type:'vocab',front:'ようじ',back:'Việc bận',kanji:'用事',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v135',type:'vocab',front:'ざんねん',back:'Tiếc, đáng tiếc',kanji:'残念',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v136',type:'vocab',front:'いっしょに',back:'Cùng với',kanji:'一緒に',lesson:'Lesson_06',sub:'Sub_01_Ru_Re_Di_Choi'},
  {id:'v137',type:'vocab',front:'たべもの',back:'Đồ ăn',kanji:'食べ物',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v138',type:'vocab',front:'のみもの',back:'Đồ uống',kanji:'飲み物',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v139',type:'vocab',front:'やきにく',back:'Thịt nướng',kanji:'焼き肉',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v140',type:'vocab',front:'らーめん',back:'Mỳ Nhật',kanji:'ラーメン',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v141',type:'vocab',front:'たべほうだい',back:'Ăn buffet',kanji:'食べ放題',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v142',type:'vocab',front:'こーす',back:'Suất ăn / Khóa học',kanji:'コース',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v143',type:'vocab',front:'いざかや',back:'Quán rượu',kanji:'居酒屋',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v144',type:'vocab',front:'えいがかん',back:'Rạp chiếu phim',kanji:'映画館',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v145',type:'vocab',front:'ちかてつ',back:'Tàu điện ngầm',kanji:'地下鉄',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v146',type:'vocab',front:'かしゅ',back:'Ca sỹ',kanji:'歌手',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v147',type:'vocab',front:'きせつ',back:'Mùa',kanji:'季節',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v148',type:'vocab',front:'こめでぃー',back:'Hài kịch',kanji:'コメディー',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v149',type:'vocab',front:'じゃず',back:'Nhạc jazz',kanji:'ジャズ',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v150',type:'vocab',front:'つあー',back:'Tour du lịch',kanji:'ツアー',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v151',type:'vocab',front:'どちら',back:'Bên nào, phương nào',kanji:'どちら',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v152',type:'vocab',front:'どちらも',back:'Bên nào cũng',kanji:'どちらも',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v153',type:'vocab',front:'ちかい',back:'Gần',kanji:'近い',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v154',type:'vocab',front:'とおい',back:'Xa',kanji:'遠い',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v155',type:'vocab',front:'はやい',back:'Sớm',kanji:'早い',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v156',type:'vocab',front:'ひろい',back:'Rộng',kanji:'広い',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v157',type:'vocab',front:'いちばん',back:'Nhất, số 1',kanji:'いちばん',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v158',type:'vocab',front:'ぜんぶ',back:'Toàn bộ, tất cả',kanji:'全部',lesson:'Lesson_06',sub:'Sub_02_Lua_Chon_Quan_An'},
  {id:'v159',type:'vocab',front:'おこのみやき',back:'Món bánh xèo Nhật',kanji:'お好み焼き',lesson:'Lesson_06',sub:'Sub_03_Mon_An_Va_Quyet_Dinh'},
  {id:'v160',type:'vocab',front:'すきやき',back:'Món nhúng có thịt bò và rau',kanji:'すき焼き',lesson:'Lesson_06',sub:'Sub_03_Mon_An_Va_Quyet_Dinh'},
  {id:'v161',type:'vocab',front:'あそびます',back:'Chơi, chơi đùa',kanji:'遊びます',lesson:'Lesson_06',sub:'Sub_03_Mon_An_Va_Quyet_Dinh'},
  {id:'v162',type:'vocab',front:'ぜひ',back:'Nhất định',kanji:'ぜひ',lesson:'Lesson_06',sub:'Sub_03_Mon_An_Va_Quyet_Dinh'},
  {id:'v163',type:'vocab',front:'まだ',back:'Vẫn, chưa',kanji:'まだ',lesson:'Lesson_06',sub:'Sub_03_Mon_An_Va_Quyet_Dinh'},
  {id:'v164',type:'vocab',front:'もう',back:'Đã, rồi',kanji:'もう',lesson:'Lesson_06',sub:'Sub_03_Mon_An_Va_Quyet_Dinh'},
  {id:'v165',type:'vocab',front:'かいさつ',back:'Soát vé',kanji:'改札',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v166',type:'vocab',front:'き',back:'Cây / Gỗ',kanji:'木',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v167',type:'vocab',front:'こうばん',back:'Đồn cảnh sát',kanji:'交番',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v168',type:'vocab',front:'じどうはんばいき',back:'Máy bán hàng tự động',kanji:'自動販売機',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v169',type:'vocab',front:'ばすてい',back:'Trạm xe buýt',kanji:'バス停',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v170',type:'vocab',front:'ぽすと',back:'Thùng thư, hòm thư',kanji:'ポスト',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v171',type:'vocab',front:'はな',back:'Hoa',kanji:'花',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v172',type:'vocab',front:'いぬ',back:'Con chó',kanji:'犬',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v173',type:'vocab',front:'あいだ',back:'Giữa, ở giữa',kanji:'間',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v174',type:'vocab',front:'うえ',back:'Trên, bên trên',kanji:'上',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v175',type:'vocab',front:'した',back:'Dưới, phía dưới',kanji:'下',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v176',type:'vocab',front:'ちかく',back:'Gần (ở vị trí gần)',kanji:'近く',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v177',type:'vocab',front:'となり',back:'Bên cạnh (cạnh sát)',kanji:'隣',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v178',type:'vocab',front:'なか',back:'Trong, bên trong',kanji:'中',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v179',type:'vocab',front:'そと',back:'Ngoài, bên ngoài',kanji:'外',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v180',type:'vocab',front:'まえ',back:'Trước, phía trước',kanji:'前',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v181',type:'vocab',front:'うしろ',back:'Sau, phía sau, đằng sau',kanji:'後ろ',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v182',type:'vocab',front:'よこ',back:'Bên cạnh, chiều ngang',kanji:'横',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v183',type:'vocab',front:'むかえにいきます',back:'Đi đón',kanji:'迎えに行きます',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v184',type:'vocab',front:'いる',back:'Có mặt ở (người, động vật)',kanji:'います',lesson:'Lesson_07',sub:'Sub_01_Hoi_Duong_Vi_Tri'},
  {id:'v185',type:'vocab',front:'いす',back:'Ghế, cái ghế',kanji:'いす',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v186',type:'vocab',front:'てーぶる',back:'Bàn, cái bàn',kanji:'テーブル',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v187',type:'vocab',front:'denしれんじ',back:'Lò vi sóng',kanji:'電子レンジ',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v188',type:'vocab',front:'れいぞうこ',back:'Tủ lạnh',kanji:'冷蔵庫',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v189',type:'vocab',front:'さtou',back:'Đường (ăn)',kanji:'砂糖',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v190',type:'vocab',front:'しお',back:'Muối',kanji:'塩',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v191',type:'vocab',front:'しょうゆ',back:'Xì dầu',kanji:'しょうゆ',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v192',type:'vocab',front:'こっぷ',back:'Cốc, cái cốc',kanji:'コップ',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v193',type:'vocab',front:'おさら',back:'Đĩa, cái đĩa',kanji:'お皿',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v194',type:'vocab',front:'すぷーん',back:'Cái thìa, cái muỗng',kanji:'スプーン',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v195',type:'vocab',front:'ないふ',back:'Dao, con dao',kanji:'ナイフ',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v196',type:'vocab',front:'ふぉーく',back:'Cái dĩa',kanji:'フォーク',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v197',type:'vocab',front:'はし',back:'Đũa',kanji:'はし',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v198',type:'vocab',front:'かんじ',back:'Chữ hán',kanji:'漢字',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v199',type:'vocab',front:'どれ',back:'Cái nào',kanji:'どれ',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v200',type:'vocab',front:'あらいます',back:'Giặt, rửa, tắm',kanji:'洗います',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v201',type:'vocab',front:'おきます',back:'Đặt, để',kanji:'置きます',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v202',type:'vocab',front:'かきます',back:'Viết',kanji:'書きます',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v203',type:'vocab',front:'かします',back:'Cho mượn',kanji:'貸します',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v204',type:'vocab',front:'ききます',back:'Nghe, hỏi',kanji:'聞きます',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v205',type:'vocab',front:'きります',back:'Cắt, gọt',kanji:'切ります',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v206',type:'vocab',front:'つかいます',back:'Dùng, sử dụng',kanji:'使います',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v207',type:'vocab',front:'てつだいます',back:'Giúp, giúp đỡ',kanji:'手伝います',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v208',type:'vocab',front:'とります',back:'Cầm, lấy',kanji:'取ります',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v209',type:'vocab',front:'もっていきます',back:'Mang đi',kanji:'持って行きます',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v210',type:'vocab',front:'わかります',back:'Hiểu, biết',kanji:'わかります',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v211',type:'vocab',front:'だします',back:'Nộp, lấy ra',kanji:'出します',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v212',type:'vocab',front:'いれます',back:'Cho vào, bỏ vào',kanji:'入れます',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v213',type:'vocab',front:'おしえます',back:'Dạy, chỉ bảo',kanji:'教えます',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v214',type:'vocab',front:'たくさん',back:'Nhiều',kanji:'たくさん',lesson:'Lesson_07',sub:'Sub_02_Chuan_Bi_Tiec_Do_Dung'},
  {id:'v215',type:'vocab',front:'うた',back:'Bài hát',kanji:'歌',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v216',type:'vocab',front:'ぎたー',back:'Đàn ghi ta',kanji:'ギター',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v217',type:'vocab',front:'だいどころ',back:'Nhà bếp',kanji:'台所',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v218',type:'vocab',front:'たばこ',back:'Thuốc lá',kanji:'たばこ',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v219',type:'vocab',front:'でんわ',back:'Điện thoại',kanji:'電話',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v220',type:'vocab',front:'ぴざ',back:'Bánh pizza',kanji:'ピザ',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v221',type:'vocab',front:'まど',back:'Cửa sổ',kanji:'窓',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v222',type:'vocab',front:'うたいます',back:'Hát',kanji:'歌います',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v223',type:'vocab',front:'すいます',back:'Hút',kanji:'吸います',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v224',type:'vocab',front:'はなします',back:'Nói chuyện',kanji:'話します',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v225',type:'vocab',front:'ひきます',back:'Chơi (nhạc cụ)',kanji:'弾きます',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v226',type:'vocab',front:'もちます',back:'Cầm, mang',kanji:'持ちます',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v227',type:'vocab',front:'あけます',back:'Mở',kanji:'開けます',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v228',type:'vocab',front:'しめます',back:'Đóng',kanji:'閉めます',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v229',type:'vocab',front:'かけます',back:'Gọi (điện thoại)',kanji:'かけます',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v230',type:'vocab',front:'もってきます',back:'Mang đến',kanji:'持って来ます',lesson:'Lesson_07',sub:'Sub_03_Trong_Bua_Tiec'},
  {id:'v231',type:'vocab',front:'りょうしん',back:'Bố mẹ (của mình)',kanji:'両親',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v232',type:'vocab',front:'ちち',back:'Bố (của mình)',kanji:'父',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v233',type:'vocab',front:'はは',back:'Mẹ (của mình)',kanji:'母',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v234',type:'vocab',front:'きょうだい',back:'Anh chị em (của mình)',kanji:'兄弟',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v235',type:'vocab',front:'あに',back:'Anh trai (của mình)',kanji:'兄',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v236',type:'vocab',front:'あね',back:'Chị gái (của mình)',kanji:'姉',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v237',type:'vocab',front:'おとうと',back:'Em trai (của mình)',kanji:'弟',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v238',type:'vocab',front:'いもうと',back:'Em gái (của mình)',kanji:'妹',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v239',type:'vocab',front:'おっと',back:'Chồng (của mình)',kanji:'夫',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v240',type:'vocab',front:'つま',back:'Vợ (của mình)',kanji:'妻',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v241',type:'vocab',front:'こども',back:'Con (của mình), trẻ con',kanji:'子ども',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v242',type:'vocab',front:'むすこ',back:'Con trai (của mình)',kanji:'息子',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v243',type:'vocab',front:'むすめ',back:'Con gái (của mình)',kanji:'娘',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v244',type:'vocab',front:'おとうさん',back:'Bố (người khác)',kanji:'お父さん',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v245',type:'vocab',front:'おかあさん',back:'Mẹ (người khác)',kanji:'お母さん',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v246',type:'vocab',front:'おにいさん',back:'Anh trai (người khác)',kanji:'お兄さん',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v247',type:'vocab',front:'おねえさん',back:'Chị gái (người khác)',kanji:'お姉さん',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v248',type:'vocab',front:'おとうとさん',back:'Em trai (người khác)',kanji:'弟さん',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v249',type:'vocab',front:'いもうとさん',back:'Em gái (người khác)',kanji:'妹さん',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v250',type:'vocab',front:'おこさん',back:'Con (người khác)',kanji:'お子さん',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v251',type:'vocab',front:'ぺっと',back:'Thú nuôi',kanji:'ペット',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v252',type:'vocab',front:'ねこ',back:'Con mèo',kanji:'猫',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v253',type:'vocab',front:'ぴあno',back:'Đàn piano',kanji:'ピアノ',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v254',type:'vocab',front:'いしゃ',back:'Bác sỹ',kanji:'医者',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v255',type:'vocab',front:'kōkōsei',back:'Học sinh cấp ba',kanji:'高校生',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v256',type:'vocab',front:'だいがくsei',back:'Sinh viên đại học',kanji:'大学生',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v257',type:'vocab',front:'すみます',back:'Sống, sinh sống',kanji:'住みます',lesson:'Lesson_08',sub:'Sub_01_Gia_Dinh_Va_Nghe_Nghiep'},
  {id:'v258',type:'vocab',front:'しゅじん',back:'Chồng (người khác)',kanji:'主人',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v259',type:'vocab',front:'おくさん',back:'Vợ (người khác)',kanji:'奥さん',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v260',type:'vocab',front:'せんぱい',back:'Tiền bối, người đi trước',kanji:'先輩',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v261',type:'vocab',front:'こうはい',back:'Hậu bối, người vào sau',kanji:'後輩',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v262',type:'vocab',front:'うさぎ',back:'Con thỏ',kanji:'うさぎ',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v263',type:'vocab',front:'からだ',back:'Thân thể, cơ thể',kanji:'体',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v264',type:'vocab',front:'あし',back:'Chân',kanji:'足',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v265',type:'vocab',front:'かお',back:'Mặt, khuôn mặt',kanji:'顔',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v266',type:'vocab',front:'かみ',back:'Tóc',kanji:'髪',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v267',type:'vocab',front:'くち',back:'Miệng',kanji:'口',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v268',type:'vocab',front:'はな',back:'Mũi',kanji:'鼻',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v269',type:'vocab',front:'め',back:'Mắt',kanji:'目',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v270',type:'vocab',front:'みみ',back:'Tai',kanji:'耳',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v271',type:'vocab',front:'あたまがいい',back:'Thông minh',kanji:'頭がいい',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v272',type:'vocab',front:'かっこいい',back:'Bảnh bao, đẹp trai',kanji:'かっこいい',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v273',type:'vocab',front:'かわいい',back:'Đáng yêu, dễ thương',kanji:'かわいい',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v274',type:'vocab',front:'せがたkai',back:'Cao (dáng người)',kanji:'背が高い',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v275',type:'vocab',front:'ながい',back:'Dài',kanji:'長い',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v276',type:'vocab',front:'みじかい',back:'Ngắn',kanji:'短い',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v277',type:'vocab',front:'やさしい',back:'Hiền lành',kanji:'優しい',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v278',type:'vocab',front:'くろい',back:'Đen, màu đen',kanji:'黒い',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v279',type:'vocab',front:'しろい',back:'Trắng, màu trắng',kanji:'白い',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v280',type:'vocab',front:'ちゃいろい',back:'Màu nâu',kanji:'茶色い',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v281',type:'vocab',front:'げんき',back:'Khỏe mạnh',kanji:'元気',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v282',type:'vocab',front:'しんせつ',back:'Tốt bụng',kanji:'親切',lesson:'Lesson_08',sub:'Sub_02_Ngoai_Hinh_Tinh_Cach'},
  {id:'v283',type:'vocab',front:'まじめ',back:'Chăm chỉ, cần mẫn',kanji:'まじめ',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v284',type:'vocab',front:'じょうず',back:'Giỏi',kanji:'上手',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v285',type:'vocab',front:'へた',back:'Kém',kanji:'下手',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v286',type:'vocab',front:'かさ',back:'Ô, cái ô',kanji:'傘',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v287',type:'vocab',front:'おかね',back:'Tiền',kanji:'お金',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v288',type:'vocab',front:'くつした',back:'Đôi tất',kanji:'靴下',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v289',type:'vocab',front:'じしょ',back:'Từ điển',kanji:'辞書',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v290',type:'vocab',front:'ちょこれーと',back:'Sô cô la',kanji:'チョコレート',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v291',type:'vocab',front:'てがみ',back:'Thư, lá thư',kanji:'手紙',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v292',type:'vocab',front:'ねっくれす',back:'Vòng cổ',kanji:'ネックレス',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v293',type:'vocab',front:'のーと',back:'Vở, quyển vở',kanji:'ノート',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v294',type:'vocab',front:'ぷれぜんと',back:'Quà, món quà',kanji:'プレゼント',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v295',type:'vocab',front:'めーる',back:'Thư điện tử',kanji:'メール',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v296',type:'vocab',front:'そぼ',back:'Bà (của mình)',kanji:'祖母',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v297',type:'vocab',front:'くりすます',back:'Giáng sinh',kanji:'クリスマス',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v298',type:'vocab',front:'けっこんしき',back:'Lễ kết hôn, đám cưới',kanji:'結婚式',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v299',type:'vocab',front:'ばれんたいんでー',back:'Ngày lễ tình nhân',kanji:'バレンタインデー',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v300',type:'vocab',front:'なにか',back:'Cái gì đó',kanji:'何か',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v301',type:'vocab',front:'おくります',back:'Gửi / Tiễn',kanji:'送ります',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v302',type:'vocab',front:'もらいます',back:'Nhận',kanji:'もらいます',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v303',type:'vocab',front:'あげます',back:'Tặng, biếu',kanji:'あげます',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v304',type:'vocab',front:'くれます',back:'Cho (mình)',kanji:'くれます',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v305',type:'vocab',front:'でんわします',back:'Gọi điện thoại',kanji:'電話します',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v306',type:'vocab',front:'もうすぐ',back:'Sắp, sắp sửa',kanji:'もうすぐ',lesson:'Lesson_08',sub:'Sub_03_Qua_Tang_Dip_Le'},
  {id:'v307',type:'vocab',front:'あくしょん',back:'Hành động (phim)',kanji:'アクション',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v308',type:'vocab',front:'おかし',back:'Bánh kẹo',kanji:'お菓子',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v309',type:'vocab',front:'きって',back:'Tem',kanji:'切手',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v310',type:'vocab',front:'くらしっく',back:'Nhạc cổ điển',kanji:'クラシック',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v311',type:'vocab',front:'ぽっぷす',back:'Nhạc Pop',kanji:'ポップス',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v312',type:'vocab',front:'しょうせつ',back:'Tiểu thuyết',kanji:'小説',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v313',type:'vocab',front:'まんが',back:'Truyện tranh',kanji:'漫画',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v314',type:'vocab',front:'つり',back:'Câu cá',kanji:'釣り',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v315',type:'vocab',front:'どらま',back:'Phim truyền hình / Kịch',kanji:'ドラマ',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v316',type:'vocab',front:'ぷーる',back:'Bể bơi',kanji:'プール',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v317',type:'vocab',front:'さいきん',back:'Gần đây',kanji:'最近',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v318',type:'vocab',front:'およぎます',back:'Bơi',kanji:'泳ぎます',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v319',type:'vocab',front:'かきます',back:'Vẽ, tả',kanji:'描きます',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v320',type:'vocab',front:'あつめます',back:'Thu thập, tập hợp',kanji:'集めます',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v321',type:'vocab',front:'うんてんします',back:'Lái (xe)',kanji:'運転します',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v322',type:'vocab',front:'とくに',back:'Đặc biệt',kanji:'特に',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v323',type:'vocab',front:'いつも',back:'Luôn, luôn luôn',kanji:'いつも',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v324',type:'vocab',front:'よく',back:'Thường, hay',kanji:'よく',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v325',type:'vocab',front:'ときどき',back:'Thỉnh thoảng, đôi khi',kanji:'ときどき',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v326',type:'vocab',front:'あまり',back:'Không lắm',kanji:'あまり',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v327',type:'vocab',front:'ぜんぜん',back:'Hoàn toàn không',kanji:'全然',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v328',type:'vocab',front:'でも',back:'Nhưng, tuy nhiên',kanji:'đem',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v329',type:'vocab',front:'だけ',back:'Chỉ',kanji:'だけ',lesson:'Lesson_09',sub:'Sub_01_So_Thich_Ca_Nhan'},
  {id:'v330',type:'vocab',front:'いべんと',back:'Sự kiện',kanji:'イベント',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v331',type:'vocab',front:'こんてすと',back:'Cuộc thi',kanji:'コンテスト',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v332',type:'vocab',front:'しょどう',back:'Thư pháp',kanji:'書道',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v333',type:'vocab',front:'だいびんぐ',back:'Sự lặn xuống',kanji:'ダイビング',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v334',type:'vocab',front:'だんす',back:'Khiêu vũ',kanji:'ダンス',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v335',type:'vocab',front:'ならいます',back:'Học',kanji:'習います',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v336',type:'vocab',front:'のります',back:'Lên (xe)',kanji:'乗ります',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v337',type:'vocab',front:'もうしこみます',back:'Xin, đăng ký',kanji:'申し込みます',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v338',type:'vocab',front:'できる',back:'Có thể',kanji:'できます',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v339',type:'vocab',front:'さんかします',back:'Tham gia',kanji:'参加します',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v340',type:'vocab',front:'すごい',back:'Tuyệt vời / Kinh khủng',kanji:'すごい',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v341',type:'vocab',front:'いろいろ',back:'Nhiều, đa dạng',kanji:'いろいろ',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v342',type:'vocab',front:'じょうずに',back:'Thành thạo',kanji:'上手に',lesson:'Lesson_09',sub:'Sub_02_Nang_Luc_Kha_Nang'},
  {id:'v343',type:'vocab',front:'うけつけ',back:'Quầy lễ tân, thường trực',kanji:'受付',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v344',type:'vocab',front:'かーど',back:'Thẻ',kanji:'カード',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v345',type:'vocab',front:'がいこくじんとうろくしょう',back:'Chứng nhận đăng ký người nước ngoài',kanji:'外国人登録証',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v346',type:'vocab',front:'じゅうしょ',back:'Địa chỉ',kanji:'住所',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v347',type:'vocab',front:'しゅくだい',back:'Bài tập về nhà',kanji:'宿題',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v348',type:'vocab',front:'でんわばんごう',back:'Số điện thoại',kanji:'電話番号',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v349',type:'vocab',front:'いいます',back:'Nói',kanji:'言います',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v350',type:'vocab',front:'はらいます',back:'Trả, chi trả',kanji:'払います',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v351',type:'vocab',front:'おります',back:'Xuống (tàu, xe)',kanji:'降ります',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v352',type:'vocab',front:'みせます',back:'Cho xem',kanji:'見せて',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v353',type:'vocab',front:'よやくします',back:'Đặt trước',kanji:'予約します',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v354',type:'vocab',front:'どうやって',back:'Làm thế nào',kanji:'どうやって',lesson:'Lesson_09',sub:'Sub_03_Lam_Thu_Tuc_Cuoi_Tuan'},
  {id:'v355',type:'vocab',front:'おんせい',back:'Âm thanh, tiếng động',kanji:'音声',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v356',type:'vocab',front:'こえ',back:'Giọng nói',kanji:'声',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v357',type:'vocab',front:'くすり',back:'Thuốc',kanji:'薬',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v358',type:'vocab',front:'みぎ',back:'Bên phải',kanji:'右',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v359',type:'vocab',front:'ひだり',back:'Bên trái',kanji:'左',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v360',type:'vocab',front:'かど',back:'Góc đường',kanji:'角',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v361',type:'vocab',front:'kōsaten',back:'Ngã tư',kanji:'交差点',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v362',type:'vocab',front:'しんごう',back:'Tín hiệu / Đèn giao thông',kanji:'信号',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v363',type:'vocab',front:'はし',back:'Cầu',kanji:'橋',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v364',type:'vocab',front:'みち',back:'Đường',kanji:'道',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v365',type:'vocab',front:'さがします',back:'Tìm kiếm/Tìm',kanji:'探します',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v366',type:'vocab',front:'のみます',back:'Uống (thuốc)',kanji:'飲みます',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v367',type:'vocab',front:'まがります',back:'Rẽ/ Quẹo',kanji:'曲がります',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v368',type:'vocab',front:'わたります',back:'Qua, băng qua',kanji:'渡ります',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v369',type:'vocab',front:'きこえます',back:'Nghe thấy / Nghe được',kanji:'聞こえます',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v370',type:'vocab',front:'みえます',back:'Nhìn thấy / Nhìn được',kanji:'見えます',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v371',type:'vocab',front:'まっすぐ',back:'Thẳng',kanji:'まっすぐ',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v372',type:'vocab',front:'ちょっと',back:'Một chút, một ít',kanji:'ちょっと',lesson:'Lesson_10',sub:'Sub_01_Chi_Duong_Am_Thanh'},
  {id:'v373',type:'vocab',front:'かーてん',back:'Rèm',kanji:'カーテン',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v374',type:'vocab',front:'きゃく',back:'Khách',kanji:'客',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v375',type:'vocab',front:'ごみ',back:'Rác',kanji:'ごみ',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v376',type:'vocab',front:'て',back:'Tay, bàn tay',kanji:'手',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v377',type:'vocab',front:'にかつ',back:'Hành lý / Bưu phẩm',kanji:'荷物',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v378',type:'vocab',front:'ぱんふれっと',back:'Tờ rơi / Tờ quảng cáo',kanji:'パンフレット',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v379',type:'vocab',front:'ほか',back:'Khác',kanji:'他',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v380',type:'vocab',front:'みなさん',back:'Mọi người',kanji:'皆さん',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v381',type:'vocab',front:'みやげ',back:'Quà (lưu niệm)',kanji:'土産',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v382',type:'vocab',front:'おします',back:'Ấn/ Đẩy',kanji:'押します',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v383',type:'vocab',front:'すわります',back:'Ngồi',kanji:'座ります',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v384',type:'vocab',front:'たちます',back:'Đứng',kanji:'立ちます',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v385',type:'vocab',front:'なくす',back:'Làm mất, đánh mất',kanji:'なくします',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v386',type:'vocab',front:'もってかえります',back:'Mang về',kanji:'持って帰ります',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v387',type:'vocab',front:'おくれます',back:'Muộn, chậm trễ',kanji:'遅れます',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v388',type:'vocab',front:'すてます',back:'Vứt, vứt bỏ',kanji:'捨てます',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v389',type:'vocab',front:'しゅうごうします',back:'Tập trung / Tập hợp',kanji:'集合します',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v390',type:'vocab',front:'あぶない',back:'Nguy hiểm',kanji:'危ない',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v391',type:'vocab',front:'たいせつ',back:'Quan trọng / Quý giá',kanji:'大切',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v392',type:'vocab',front:'めいわく',back:'Phiền phức',kanji:'迷惑',lesson:'Lesson_10',sub:'Sub_02_Cac_Bien_Bao_Chu_Y'},
  {id:'v393',type:'vocab',front:'どうぶつえん',back:'Vườn bách thú',kanji:'動物園',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v394',type:'vocab',front:'くま',back:'Con gấu',kanji:'クマ',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v395',type:'vocab',front:'こあら',back:'Con gấu Kao-la',kanji:'コアラ',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v396',type:'vocab',front:'さる',back:'Con khỉ',kanji:'サル',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v397',type:'vocab',front:'ぞう',back:'Con voi',kanji:'ゾウ',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v398',type:'vocab',front:'とり',back:'Con chim',kanji:'鳥',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v399',type:'vocab',front:'ぱんだ',back:'Con gấu trúc',kanji:'パンダ',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v400',type:'vocab',front:'ぺんぎん',back:'Con chim cánh cụt',kanji:'ペンギン',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v401',type:'vocab',front:'いりぐち',back:'Cửa vào / Lối vào',kanji:'入り口',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v402',type:'vocab',front:'でぐち',back:'Cửa ra / Lối ra',kanji:'出口',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v403',type:'vocab',front:'えさ',back:'Mồi / Thức ăn cho động vật',kanji:'えさ',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v404',type:'vocab',front:'おなか',back:'Bụng',kanji:'おなか',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v405',type:'vocab',front:'かんらんしゃ',back:'Vòng đu quay',kanji:'観覧車',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v406',type:'vocab',front:'ばなな',back:'Chuối',kanji:'バナナ',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v407',type:'vocab',front:'ぼーる',back:'Bóng',kanji:'ボール',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v408',type:'vocab',front:'あるきます',back:'Đi bộ',kanji:'歩きます',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v409',type:'vocab',front:'とびます',back:'Bay',kanji:'飛びます',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v410',type:'vocab',front:'なる',back:'Trở nên/ Trở thành',kanji:'なります',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v411',type:'vocab',front:'やすみます',back:'Nghỉ',kanji:'休みます',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v412',type:'vocab',front:'やる',back:'Cho, làm',kanji:'やります',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v413',type:'vocab',front:'おなかがすきます',back:'Đói',kanji:'おなかがすきます',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v414',type:'vocab',front:'のどがかわきます',back:'Khát',kanji:'のどがかわきます',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v415',type:'vocab',front:'つかれます',back:'Mệt',kanji:'疲れます',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v416',type:'vocab',front:'いたい',back:'Đau',kanji:'痛い',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v417',type:'vocab',front:'くらい',back:'Tối',kanji:'暗い',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v418',type:'vocab',front:'そろそろ',back:'Đến lúc phải , sắp',kanji:'そろそろ',lesson:'Lesson_10',sub:'Sub_03_Tai_Vuon_Bach_Thu'},
  {id:'v419',type:'vocab',front:'あたま',back:'Đầu',kanji:'頭',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v420',type:'vocab',front:'かいわ',back:'Hội thoại',kanji:'会話',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v421',type:'vocab',front:'さくぶん',back:'Tập làm văn, viết văn',kanji:'作文',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v422',type:'vocab',front:'くらすめいと',back:'Bạn cùng lớp',kanji:'クラスメイト',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v423',type:'vocab',front:'ざっし',back:'Tạp chí',kanji:'雑誌',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v424',type:'vocab',front:'じょぎんぐ',back:'Chạy bộ (tập thể dục)',kanji:'ジョギング',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v425',type:'vocab',front:'せいかつ',back:'Cuộc sống, sinh hoạt',kanji:'生活',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v426',type:'vocab',front:'てんちょう',back:'Chủ cửa hàng, cửa hàng trưởng',kanji:'店長',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v427',type:'vocab',front:'にっき',back:'Nhật kí',kanji:'日記',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v428',type:'vocab',front:'はじめ',back:'Đầu, ban đầu',kanji:'初め',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v429',type:'vocab',front:'ひとりぐらし',back:'Sống một mình',kanji:'一人暮らし',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v430',type:'vocab',front:'ひらがな',back:'Chữ Hiragana',kanji:'ひらがな',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v431',type:'vocab',front:'へいじつ',back:'Ngày thường',kanji:'平日',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v432',type:'vocab',front:'まいしゅう',back:'Hàng tuần',kanji:'毎週',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v433',type:'vocab',front:'おわります',back:'Kết thúc',kanji:'終わります',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v434',type:'vocab',front:'かよいます',back:'Đi (học, làm)',kanji:'通います',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v435',type:'vocab',front:'ひく',back:'Bị (cảm)',kanji:'ひきます',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v436',type:'vocab',front:'やすみます',back:'Nghỉ',kanji:'休みます',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v437',type:'vocab',front:'なれます',back:'Quen',kanji:'慣れます',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v438',type:'vocab',front:'わすれます',back:'Quên',kanji:'忘れます',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v439',type:'vocab',front:'sanぽします',back:'Đi dạo',kanji:'散歩します',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v440',type:'vocab',front:'さびしい',back:'Buồn, cô đơn',kanji:'寂しい',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v441',type:'vocab',front:'ねむい',back:'Buồn ngủ',kanji:'眠い',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v442',type:'vocab',front:'たいてい',back:'Đại để/ Đại khái',kanji:'たいてい',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v443',type:'vocab',front:'なかなか',back:'Mãi mà',kanji:'nanaか',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v444',type:'vocab',front:'ええ',back:'Ừ / Vâng',kanji:'ええ',lesson:'Lesson_11',sub:'Sub_01_Cuoc_Song_Hien_Tai'},
  {id:'v445',type:'vocab',front:'おりんぴっく',back:'Đại hội thể thao Olympic',kanji:'オリンピック',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v446',type:'vocab',front:'गाईこく',back:'Nước ngoài',kanji:'外国',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v447',type:'vocab',front:'しょうがくせい',back:'Học sinh tiểu học, cấp 1',kanji:'小学生',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v448',type:'vocab',front:'ちゅうがくせい',back:'Học sinh trung học, cấp 2',kanji:'中学生',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v449',type:'vocab',front:'せんしゅ',back:'Tuyển thủ / Cầu thủ',kanji:'選手',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v450',type:'vocab',front:'そふ',back:'Ông (của mình)',kanji:'祖父',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v451',type:'vocab',front:'はじめます',back:'Bắt đầu',kanji:'始めます',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v452',type:'vocab',front:'わかれます',back:'Chia tay',kanji:'別れます',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v453',type:'vocab',front:'そつぎょうします',back:'Tốt nghiệp',kanji:'卒業します',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v454',type:'vocab',front:'にゅうがくします',back:'Nhập học',kanji:'入学します',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v455',type:'vocab',front:'だんだん',back:'Dần dần',kanji:'だんだん',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v456',type:'vocab',front:'はじめて',back:'Lần đầu tiên',kanji:'初めて',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v457',type:'vocab',front:'それで',back:'Vì thế / Vì vậy',kanji:'それで',lesson:'Lesson_11',sub:'Sub_02_Thay_Doi_Ban_Than'},
  {id:'v458',type:'vocab',front:'えあこん',back:'Điều hòa',kanji:'エアコン',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v459',type:'vocab',front:'にゅーす',back:'Tin tức',kanji:'ニュース',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v460',type:'vocab',front:'けします',back:'Tắt',kanji:'消します',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v461',type:'vocab',front:'つけます',back:'Bật',kanji:'つけます',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v462',type:'vocab',front:'ひっこしします',back:'Chuyển nhà',kanji:'引越しします',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v463',type:'vocab',front:'うん',back:'Vâng / Dạ (thân mật)',kanji:'うん',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v464',type:'vocab',front:'ううん',back:'Không / Không phải (thân mật)',kanji:'ううん',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v465',type:'vocab',front:'ごめん',back:'Xin lỗi!',kanji:'ごめん',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v466',type:'vocab',front:'そっか',back:'Thế à!',kanji:'そっか',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v467',type:'vocab',front:'また',back:'Lại',kanji:'また',lesson:'Lesson_11',sub:'Sub_03_Hoi_Thoai_Thân_Mat'},
  {id:'v468',type:'vocab',front:'けが',back:'Vết thương',kanji:'けが',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v469',type:'vocab',front:'しょくよく',back:'Sự thèm ăn / Sự ngon miệng',kanji:'食欲',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v470',type:'vocab',front:'ちょうし',back:'Tình trạng (sức khỏe, máy móc)',kanji:'調子',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v471',type:'vocab',front:'ねつ',back:'Nhiệt độ / Sốt',kanji:'熱',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v472',type:'vocab',front:'びょうき',back:'Bệnh / Ốm',kanji:'病気',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v473',type:'vocab',front:'のど',back:'Họng',kanji:'のど',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v474',type:'vocab',front:'なおります',back:'Khỏi',kanji:'治ります',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v475',type:'vocab',front:'わるい',back:'Xấu, tồi',kanji:'悪い',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v476',type:'vocab',front:'は',back:'Răng',kanji:'歯',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v477',type:'vocab',front:'のみかい',back:'Bữa nhậu',kanji:'飲み会',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v478',type:'vocab',front:'きもちがわるい',back:'Khó chịu (tâm trạng xấu)',kanji:'気持ちが悪い',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v479',type:'vocab',front:'だいじょうぶ',back:'Ổn, không sao',kanji:'大丈夫',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v480',type:'vocab',front:'はやく',back:'Sớm',kanji:'早く',lesson:'Lesson_12',sub:'Sub_01_Tinh_Trang_Suc_Khoe'},
  {id:'v481',type:'vocab',front:'あどばいす',back:'Lời khuyên',kanji:'アドバイス',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v482',type:'vocab',front:'しゃわー',back:'Vòi hoa sen',kanji:'シャワー',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v483',type:'vocab',front:'すいmin',back:'Giấc ngủ/ Việc ngủ',kanji:'睡眠',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v484',type:'vocab',front:'はいしゃ',back:'Nha sĩ',kanji:'歯医者',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v485',type:'vocab',front:'やけど',back:'Bỏng / Vết bỏng',kanji:'やけど',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v486',type:'vocab',front:'こと',back:'Việc',kanji:'こと',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v487',type:'vocab',front:'もの',back:'Vật / Đồ vật',kanji:'もの',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v488',type:'vocab',front:'いじょう',back:'Trên / Hơn',kanji:'以上',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v489',type:'vocab',front:'だします',back:'Lấy ra/ Đưa ra/ lên tiếng',kanji:'出します',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v490',type:'vocab',front:'ぬります',back:'Sơn, bôi',kanji:'塗ります',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v491',type:'vocab',front:'あびます',back:'Tắm',kanji:'浴びます',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v492',type:'vocab',front:'でかけます',back:'Đi ra ngoài',kanji:'出かけます',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v493',type:'vocab',front:'うんどうします',back:'Tập thể dục',kanji:'運動します',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v494',type:'vocab',front:'かたい',back:'Cứng',kanji:'固い',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v495',type:'vocab',front:'やわらかい',back:'Mềm',kanji:'柔らかい',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v496',type:'vocab',front:'じぶんで',back:'Tự mình',kanji:'自分で',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v497',type:'vocab',front:'できるだけ',back:'Cố gắng hết sức',kanji:'できるだけ',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v498',type:'vocab',front:'ゆっくり',back:'Thong thả / Từ từ',kanji:'ゆっくり',lesson:'Lesson_12',sub:'Sub_02_Loi_Khuyen_Y_Te'},
  {id:'v499',type:'vocab',front:'やくざいし',back:'Dược sĩ',kanji:'薬剤師',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v500',type:'vocab',front:'うわぎ',back:'Áo khoác',kanji:'上着',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v501',type:'vocab',front:'こんたくとれんず',back:'Kính áp tròng',kanji:'コンタクトレンズ',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v502',type:'vocab',front:'せつめいしょ',back:'Sách hướng dẫn',kanji:'説明書',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v503',type:'vocab',front:'おふろ',back:'Bồn tắm',kanji:'お風呂',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v504',type:'vocab',front:'ほけんしょう',back:'Thẻ bảo hiểm',kanji:'保険証',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v505',type:'vocab',front:'まちあいしつ',back:'Phòng chờ',kanji:'待合室',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v506',type:'vocab',front:'やっきょく',back:'Hiệu thuốc',kanji:'薬局',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v507',type:'vocab',front:'だします',back:'Xuất trình / Nộp',kanji:'出します',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v508',type:'vocab',front:'ぬぎます',back:'Cởi',kanji:'脱ぎます',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v509',type:'vocab',front:'はしります',back:'Chạy',kanji:'走ります',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v510',type:'vocab',front:'まちます',back:'Đợi Chờ',kanji:'待ちます',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v511',type:'vocab',front:'みがきます',back:'Đánh (răng, giày)',kanji:'磨きます',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v512',type:'vocab',front:'よこになります',back:'Nằm',kanji:'横になります',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v513',type:'vocab',front:'じゅんびします',back:'Chuẩn bị',kanji:'準備します',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v514',type:'vocab',front:'かゆい',back:'Ngứa',kanji:'かゆい',lesson:'Lesson_12',sub:'Sub_03_Kham_Benh_Nha_Thuoc'},
  {id:'v515',type:'vocab',front:'こうよう',back:'Lá đỏ',kanji:'紅葉',lesson:'Lesson_13',sub:'Sub_01_Kinh_Nghiem_Du_Lich'},
  {id:'v516',type:'vocab',front:'さーびす',back:'Dịch vụ',kanji:'サービス',lesson:'Lesson_13',sub:'Sub_01_Kinh_Nghiem_Du_Lich'},
  {id:'v517',type:'vocab',front:'すもう',back:'Vật Sumo',kanji:'相撲',lesson:'Lesson_13',sub:'Sub_01_Kinh_Nghiem_Du_Lich'},
  {id:'v518',type:'vocab',front:'ほてる',back:'Khách sạn',kanji:'ホテル',lesson:'Lesson_13',sub:'Sub_01_Kinh_Nghiem_Du_Lich'},
  {id:'v519',type:'vocab',front:'しります',back:'Biết',kanji:'知ります',lesson:'Lesson_13',sub:'Sub_01_Kinh_Nghiem_Du_Lich'},
  {id:'v520',type:'vocab',front:'でーとします',back:'Hẹn hò',kanji:'デートします',lesson:'Lesson_13',sub:'Sub_01_Kinh_Nghiem_Du_Lich'},
  {id:'v521',type:'vocab',front:'おとcのひと',back:'Đàn ông',kanji:'男の人',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v522',type:'vocab',front:'おんなのひと',back:'Phụ nữ',kanji:'女の人',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v523',type:'vocab',front:'おみせ',back:'Cửa hàng',kanji:'お店',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v524',type:'vocab',front:'ゆうえんち',back:'Khu vui chơi',kanji:'遊園地',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v525',type:'vocab',front:'じぇっとこーすたー',back:'Tàu lượn',kanji:'ジェットコースター',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v526',type:'vocab',front:'でんきせいひん',back:'Đồ điện',kanji:'電気製品',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v527',type:'vocab',front:'さんぐらす',back:'Kính mát, kính râm',kanji:'サングラス',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v528',type:'vocab',front:'めがね',back:'Kính',kanji:'眼鏡',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v529',type:'vocab',front:'しゃつ',back:'Áo sơ mi',kanji:'シャツ',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v530',type:'vocab',front:'すかーと',back:'Váy (ngắn), juýp',kanji:'スカート',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v531',type:'vocab',front:'ねくたい',back:'Cà vạt',kanji:'ネクタイ',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v532',type:'vocab',front:'ぼうし',back:'Mũ',kanji:'帽子',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v533',type:'vocab',front:'にんき',back:'Sự được yêu thích, được mến mộ',kanji:'人気',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v534',type:'vocab',front:'うります',back:'Bán',kanji:'売ります',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v535',type:'vocab',front:'かぶります',back:'Đội (mũ)',kanji:'かぶります',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v536',type:'vocab',front:'とまります',back:'Trọ lại, nghỉ lại',kanji:'泊まります',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v537',type:'vocab',front:'はきます',back:'Đi (giầy, tất), mặc (quần, váy)',kanji:'はきます',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v538',type:'vocab',front:'かけます',back:'Đeo / Treo',kanji:'かけます',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v539',type:'vocab',front:'きます',back:'Mặc',kanji:'着ます',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v540',type:'vocab',front:'する',back:'Đeo / Mặc (phụ kiện)',kanji:'します',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v541',type:'vocab',front:'あおい',back:'Xanh',kanji:'青い',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v542',type:'vocab',front:'あkai',back:'Đỏ',kanji:'赤い',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v543',type:'vocab',front:'きいろい',back:'Vàng',kanji:'黄色い',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v544',type:'vocab',front:'わかい',back:'Trẻ',kanji:'若い',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v545',type:'vocab',front:'しんせん',back:'Tươi, mới',kanji:'新鮮',lesson:'Lesson_13',sub:'Sub_02_Trang_Phuc_Mua_Sam'},
  {id:'v546',type:'vocab',front:'ざいりょう',back:'Tài liệu, vật liệu, nguyên liệu',kanji:'材料',lesson:'Lesson_13',sub:'Sub_03_Su_Kien_Le_Hoi'},
  {id:'v547',type:'vocab',front:'ばしょ',back:'Địa điểm',kanji:'場所',lesson:'Lesson_13',sub:'Sub_03_Su_Kien_Le_Hoi'},
  {id:'v548',type:'vocab',front:'ばすけっとぼーる',back:'Bóng rổ',kanji:'バスケットボール',lesson:'Lesson_13',sub:'Sub_03_Su_Kien_Le_Hoi'},
  {id:'v549',type:'vocab',front:'ゆかた',back:'Trang phục Yukata (Kimono mặc mùa hè)',kanji:'浴衣',lesson:'Lesson_13',sub:'Sub_03_Su_Kien_Le_Hoi'},
  {id:'v550',type:'vocab',front:'どこか',back:'Chỗ nào đó',kanji:'どこか',lesson:'Lesson_13',sub:'Sub_03_Su_Kien_Le_Hoi'},
  {id:'v551',type:'vocab',front:'れんしゅうします',back:'Luyện tập',kanji:'練習します',lesson:'Lesson_13',sub:'Sub_03_Su_Kien_Le_Hoi'},
  {id:'v552',type:'vocab',front:'うどん',back:'Món mì udon',kanji:'うどん',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v553',type:'vocab',front:'そば',back:'Món mì soba',kanji:'そば',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v554',type:'vocab',front:'かいろ',back:'カイロ (vật bỏ túi để làm ấm)',kanji:'カイロ',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v555',type:'vocab',front:'こたつ',back:'Bàn có lò sưởi đặt dưới sàn',kanji:'こたつ',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v556',type:'vocab',front:'じ',back:'Chữ, ký tự',kanji:'字',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v557',type:'vocab',front:'しょっけん',back:'Phiếu ăn',kanji:'食券',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v558',type:'vocab',front:'おつり',back:'Tiền thừa, tiền trả lại',kanji:'お釣り',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v559',type:'vocab',front:'でんき',back:'Điện, đèn',kanji:'電気',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v560',type:'vocab',front:'どあ',back:'Cửa ra vào',kanji:'ドア',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v561',type:'vocab',front:'とうがらし',back:'Ớt',kanji:'唐辛子',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v562',type:'vocab',front:'ふうりん',back:'Chuông gió',kanji:'風鈴',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v563',type:'vocab',front:'ふとん',back:'Chăn',kanji:'布団',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v564',type:'vocab',front:'ぽけっと',back:'Túi quần, túi áo',kanji:'ポケット',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v565',type:'vocab',front:'ぼたん',back:'Nút bấm, khuy áo',kanji:'ボタン',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v566',type:'vocab',front:'おゆ',back:'Nước nóng',kanji:'お湯',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v567',type:'vocab',front:'ゆたんぽ',back:'Túi chườm',kanji:'湯たんぽ',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v568',type:'vocab',front:'ればー',back:'Cần gạt, đòn bẩy',kanji:'レバー',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v569',type:'vocab',front:'あきます',back:'(cửa) Mở',kanji:'開きます',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v570',type:'vocab',front:'さわります',back:'Sờ, chạm',kanji:'触ります',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v571',type:'vocab',front:'つく',back:'(đèn) Bật / Sáng',kanji:'つきます',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v572',type:'vocab',front:'まわします',back:'Xoay, quay',kanji:'回します',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v573',type:'vocab',front:'でます',back:'(nước, tiền) Chảy ra',kanji:'出ます',lesson:'Lesson_14',sub:'Sub_01_Lan_Dau_Trai_Nghiem'},
  {id:'v574',type:'vocab',front:'いか',back:'Dưới đây, sau đây',kanji:'以下',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v575',type:'vocab',front:'げんかん',back:'Hiên nhà, sảnh trong nhà',kanji:'玄関',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v576',type:'vocab',front:'しーとべると',back:'Dây an toàn',kanji:'シートベルト',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v577',type:'vocab',front:'せいふく',back:'Đồng phục',kanji:'制服',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v578',type:'vocab',front:'ばいく',back:'Xe máy',kanji:'バイク',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v579',type:'vocab',front:'へるめっと',back:'Mũ bảo hiểm',kanji:'ヘルメット',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v580',type:'vocab',front:'ぱすぽーと',back:'Hộ chiếu',kanji:'パスポート',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v581',type:'vocab',front:'みぶんしょう',back:'Chứng minh thư, thẻ căn cước',kanji:'身分証',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v582',type:'vocab',front:'りょうきん',back:'Phí, cước',kanji:'料金',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v583',type:'vocab',front:'にゅうじょうりょう',back:'Phí vào cửa',kanji:'入場料',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v584',type:'vocab',front:'ならびます',back:'Xếp hàng, được xếp',kanji:'並びます',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v585',type:'vocab',front:'とめます',back:'Dừng, đỗ',kanji:'止めます',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v586',type:'vocab',front:'わけます',back:'Chia',kanji:'分けます',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v587',type:'vocab',front:'きちんと',back:'Chỉnh chu, cẩn thận',kanji:'きちんと',lesson:'Lesson_14',sub:'Sub_02_Luat_Le_Van_Hoa'},
  {id:'v588',type:'vocab',front:'いなか',back:'Quê, nông thôn',kanji:'田舎',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v589',type:'vocab',front:'とかい',back:'Thành thị',kanji:'都会',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v590',type:'vocab',front:'くうき',back:'Không khí',kanji:'空気',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v591',type:'vocab',front:'こうつう',back:'Giao thông',kanji:'交通',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v592',type:'vocab',front:'じきゅう',back:'Lương theo giờ',kanji:'時給',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v593',type:'vocab',front:'じゆう',back:'Tự do',kanji:'自由',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v594',type:'vocab',front:'でざいん',back:'Thiết kế',kanji:'デザイン',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v595',type:'vocab',front:'ばんぐみ',back:'Chương trình',kanji:'番組',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v596',type:'vocab',front:'ふぁすとふーど',back:'Đồ ăn nhanh',kanji:'ファストフード',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v597',type:'vocab',front:'ふぁっしょん',back:'Thời trang',kanji:'ファッション',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v598',type:'vocab',front:'ふりーぷらん',back:'Tour du lịch tự do',kanji:'フリープラン',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v599',type:'vocab',front:'おもいます',back:'Nghĩ rằng / Cho rằng',kanji:'思います',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v600',type:'vocab',front:'けしょうします',back:'Trang điểm',kanji:'化粧します',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v601',type:'vocab',front:'けいけんします',back:'Trải nghiệm',kanji:'経験します',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v602',type:'vocab',front:'うるさい',back:'Ầm ĩ, ồn ào',kanji:'うるさい',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v603',type:'vocab',front:'おしゃれ',back:'Ăn diện, hợp thời trang',kanji:'おしゃれ',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v604',type:'vocab',front:'ふくざつ',back:'Phức tạp',kanji:'複雑',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v605',type:'vocab',front:'べんり',back:'Tiện lợi',kanji:'便利',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v606',type:'vocab',front:'ふべん',back:'Bất tiện',kanji:'不便',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v607',type:'vocab',front:'いつでも',back:'Bất cứ khi nào',kanji:'いつでも',lesson:'Lesson_14',sub:'Sub_03_Neu_Y_Kien_Ca_Nhan'},
  {id:'v608',type:'vocab',front:'がらす',back:'Kính / Cốc thủy tinh',kanji:'ガラス',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v609',type:'vocab',front:'くもり',back:'Trời nhiều mây',kanji:'曇り',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v610',type:'vocab',front:'たいふう',back:'Bão',kanji:'台風',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v611',type:'vocab',front:'じしん',back:'Động đất',kanji:'地震',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v612',type:'vocab',front:'じこ',back:'Sự cố, tai nạn',kanji:'事故',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v613',type:'vocab',front:'ちーむ',back:'Đội',kanji:'チーム',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v614',type:'vocab',front:'ちゅうし',back:'Hoãn, dừng lại',kanji:'中止',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v615',type:'vocab',front:'ふりーまーけっと',back:'Chợ trời',kanji:'フリーマーケット',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v616',type:'vocab',front:'ほんとう',back:'Sự thật',kanji:'本当',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v617',type:'vocab',front:'むかし',back:'Ngày xưa',kanji:'昔',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v618',type:'vocab',front:'むりょう',back:'Miễn phí',kanji:'無料',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v619',type:'vocab',front:'ゆうがた',back:'Chiều tối, hoàng hôn',kanji:'夕方',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v620',type:'vocab',front:'しにます',back:'Chết',kanji:'死にます',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v621',type:'vocab',front:'なくなります',back:'Mất, hết',kanji:'亡くなります',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v622',type:'vocab',front:'とまります',back:'(máy) Dừng',kanji:'止まります',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v623',type:'vocab',front:'はじまります',back:'(giờ học) Bắt đầu',kanji:'始まります',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v624',type:'vocab',front:'ふります',back:'Rơi',kanji:'降ります',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v625',type:'vocab',front:'かちます',back:'Thắng, chiến thắng',kanji:'勝ちます',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v626',type:'vocab',front:'まけます',back:'Thua, thất bại',kanji:'負けます',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v627',type:'vocab',front:'たおれます',back:'Đổ',kanji:'倒れます',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v628',type:'vocab',front:'できる',back:'Được hoàn thành, xong',kanji:'できます',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v629',type:'vocab',front:'われます',back:'Vỡ',kanji:'割れます',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v630',type:'vocab',front:'けっこんします',back:'Cưới, kết hôn',kanji:'結婚します',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v631',type:'vocab',front:'にゅういんします',back:'Nhập viện',kanji:'入院します',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v632',type:'vocab',front:'こわい',back:'Sợ / Đáng sợ',kanji:'怖い',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v633',type:'vocab',front:'しんぱい',back:'Lo lắng',kanji:'心配',lesson:'Lesson_15',sub:'Sub_01_Tin_Tuc_Thien_Tai'},
  {id:'v634',type:'vocab',front:'かぜ',back:'Gió',kanji:'風',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v635',type:'vocab',front:'すとらっぷ',back:'Dây đeo điện thoại',kanji:'ストラップ',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v636',type:'vocab',front:'せき',back:'Chỗ ngồi',kanji:'席',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v637',type:'vocab',front:'いそぎます',back:'Vội vàng',kanji:'急ぎます',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v638',type:'vocab',front:'こみます',back:'Đông',kanji:'混みます',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v639',type:'vocab',front:'まニアいます',back:'Kịp',kanji:'間に合います',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v640',type:'vocab',front:'やみます',back:'Tạnh (mưa)',kanji:'やみます',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v641',type:'vocab',front:'はれます',back:'Trời quang đãng, nắng ấm',kanji:'晴れます',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v642',type:'vocab',front:'つよい',back:'Mạnh',kanji:'強い',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v643',type:'vocab',front:'きっと',back:'Chắc chắn',kanji:'きっと',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v644',type:'vocab',front:'たぶん',back:'Có lẽ',kanji:'たぶん',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v645',type:'vocab',front:'もし',back:'Nếu',kanji:'もし',lesson:'Lesson_15',sub:'Sub_02_Trang_Thai_Giam_Gia'},
  {id:'v646',type:'vocab',front:'あつまります',back:'Tập trung, tụ họp lại',kanji:'集まります',lesson:'Lesson_15',sub:'Sub_03_Tinh_Trang_Pho_Xa'},
  {id:'v647',type:'vocab',front:'しまります',back:'(cửa) Đóng',kanji:'閉まります',lesson:'Lesson_15',sub:'Sub_03_Tinh_Trang_Pho_Xa'},
  {id:'v648',type:'vocab',front:'すく',back:'Vắng / Rỗng',kanji:'すきます',lesson:'Lesson_15',sub:'Sub_03_Tinh_Trang_Pho_Xa'},
  {id:'v649',type:'vocab',front:'おちます',back:'Rơi',kanji:'落ちます',lesson:'Lesson_15',sub:'Sub_03_Tinh_Trang_Pho_Xa'},
  {id:'v650',type:'vocab',front:'きえます',back:'(đèn) Tắt / Biến mất',kanji:'消えます',lesson:'Lesson_15',sub:'Sub_03_Tinh_Trang_Pho_Xa'},
  {id:'v651',type:'vocab',front:'こわれます',back:'Hỏng',kanji:'壊れます',lesson:'Lesson_15',sub:'Sub_03_Tinh_Trang_Pho_Xa'},
  {id:'v652',type:'vocab',front:'よごれます',back:'Bẩn, vấy bẩn',kanji:'汚れます',lesson:'Lesson_15',sub:'Sub_03_Tinh_Trang_Pho_Xa'}
];